### ISSUE TITLE
[Enhancement request] Order "Playlist" screen

### ISSUE THREAD

**Issue by manuelmaniero** [michaelherger/lms-plugin-tidal#77] opened 2024-04-11 05:36 UTC
Initially, the "Playlist" screen was sorted in alphabetical order. After the clean in the code done by philippe44, playlists now figure out in another order. Is it possible to add an option for choosing the order? (Name, date modified...)
Low priority. 

Thanks a lot

**Comment by michaelherger** [comment] 2024-04-12 08:21
duplicate of #30

**Closed by michaelherger** 2024-04-12 08:21 UTC
