### ISSUE TITLE
[Feature Request] Add "Tidal" in Media Sources Search 

### ISSUE THREAD

**Issue by manuelmaniero** [michaelherger/lms-plugin-tidal#33] opened 2024-02-17 16:57 UTC
If I try to search something in "music sources" search bar, I am able to get results from YouTube (example) but not from Tidal.
Could be interesting to have "Tidal" option. An idea for this type of search could be use the "Everything" search mode already available in the plugin; with old Tidal plugin (mysqueezebox) this option was available
Thanks in advance for an evaluation and implementation.

![search1](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/a21e2929-7ed1-4c7c-8eb4-4fa4ae3c0733)
![search2](https://github.com/michaelherger/lms-plugin-tidal/assets/28586761/53083cab-9203-49f0-9b28-acbe1450410b)

**Comment by Gabba35** [comment] 2024-02-20 04:48
This would be very helpful to me also. 
I must say, the plugin is fantastic by the way, huge thanks! Especially to do it so quickly.

**Comment by michaelherger** [comment] 2024-02-20 05:39
Duplicate of #25.

**Closed by michaelherger** 2024-02-20 05:39 UTC
